### ISSUE TITLE
Support for platform (os.type=Linux os.arch=arm64)

### ISSUE THREAD

**Issue by Donkaos501** [opticdev/optic#1271]
```
root@instance-20220117-2026:/home/StraemDk/default/opentogethertube-0.2.0# yarn
yarn install v1.22.19
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning @vue/cli > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @vue/cli > @vue/cli-shared-utils > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @vue/cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @vue/cli > @vue/cli-shared-utils > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @vue/cli > @vue/cli-shared-utils > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning @vue/cli > request > har-validator@5.1.5: this library is no longer supported
warning @vue/cli > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @vue/cli > @vue/cli-shared-utils > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning @vue/cli > @vue/cli-shared-utils > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
warning @vue/cli > @vue/cli-shared-utils > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning @vue/cli > @vue/cli-shared-utils > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning @vue/cli > @vue/cli-shared-utils > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning @vue/cli > jscodeshift > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > apollo-server-core > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > apollo-server-core > graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > graphql-tools > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > nodemon > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning @vue/cli > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @vue/cli > jscodeshift > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning @vue/cli > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > apollo-server-core > apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > apollo-server-core > graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > apollo-server-express > apollo-server-core > apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
warning @vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > nodemon > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @useoptic/cli@9.0.20: This version of Optic is now deprecated. Please check the repository at https://github.com/opticdev/optic for the latest information.
warning @useoptic/cli > cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @useoptic/cli > @oclif/plugin-not-found > cli-ux@5.6.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @useoptic/cli > analytics-node > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @useoptic/cli > @useoptic/cli-server > @useoptic/ui@9.0.20: This version of Optic is now deprecated. Please check the repository at https://github.com/opticdev/optic for the latest information.
warning @useoptic/cli > @useoptic/analytics > @hapi/joi@17.1.1: Switch to 'npm install joi'
warning @useoptic/cli > @useoptic/analytics > @hapi/joi > @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
warning @useoptic/cli > @useoptic/cli-shared > wait-on > @hapi/joi@17.1.1: Switch to 'npm install joi'
warning @useoptic/cli > @useoptic/cli-shared > wait-on > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @useoptic/cli > @useoptic/cli-shared > wait-on > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @useoptic/cli > @useoptic/cli-server > @useoptic/diff-engine@9.0.20: This version of Optic is now deprecated. Please check the repository at https://github.com/opticdev/optic for the latest information.
warning @useoptic/cli > @useoptic/cli-shared > @useoptic/diff-engine@9.0.20: This version of Optic is now deprecated. Please check the repository at https://github.com/opticdev/optic for the latest information.
warning @useoptic/cli > @useoptic/cli-server > @useoptic/ui > lodash.compose@2.4.1: This package is discontinued. Use lodash.flowright@^3.0.0.
warning @useoptic/cli > @useoptic/cli-shared > mockttp > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning @useoptic/cli > @useoptic/cli-shared > mockttp > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @useoptic/cli > @useoptic/cli-shared > aws-sdk > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @useoptic/cli > @useoptic/cli-shared > aws-sdk > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @useoptic/cli > @useoptic/analytics > joi-extract-type > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning @useoptic/cli > @useoptic/analytics > @hapi/joi > @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
warning @useoptic/cli > @useoptic/analytics > @hapi/joi > @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
warning @vue/cli-plugin-babel > @vue/cli-shared-utils > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning @vue/cli-plugin-babel > @vue/cli-shared-utils > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @vue/cli-plugin-babel > webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @vue/cli-plugin-babel > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning @vue/cli-plugin-e2e-cypress > cypress > debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @vue/cli-plugin-e2e-cypress > cypress > request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
warning @vue/cli-plugin-e2e-cypress > cypress > request > har-validator@5.1.5: this library is no longer supported
warning @vue/cli-plugin-e2e-cypress > cypress > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @vue/cli-plugin-e2e-cypress > cypress > extract-zip > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @vue/cli-plugin-eslint > eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
warning @vue/cli-plugin-unit-jest > jest-environment-jsdom-fifteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @vue/cli-plugin-unit-jest > jest-environment-jsdom-fifteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @vue/cli-plugin-unit-jest > babel-plugin-transform-es2015-modules-commonjs > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @vue/cli-plugin-unit-jest > babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @vue/cli-plugin-unit-jest > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @vue/cli-plugin-unit-jest > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @vue/cli-plugin-unit-jest > babel-jest > @jest/transform > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning @vue/cli-plugin-unit-jest > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning @vue/cli-plugin-unit-jest > vue-jest > extract-from-css > css > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @vue/cli-plugin-unit-jest > vue-jest > extract-from-css > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @vue/cli-service > html-webpack-plugin@3.2.0: 3.x is no longer supported
warning @vue/cli-service > webpack-dev-server > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning @vue/cli-service > copy-webpack-plugin > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @vue/cli-service > @intervolga/optimize-cssnano-plugin > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning @vue/cli-service > @intervolga/optimize-cssnano-plugin > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning babel-jest > @jest/transform > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning core-js@3.6.4: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning supertest > superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
warning supertest > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning typescript-eslint-parser@22.0.0: Deprecated: Use @typescript-eslint/parser instead
warning typescript-eslint-parser > typescript-estree@18.0.0: This package was moved to @typescript-eslint/typescript-estree, please install the latest version from there instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ts-loader@9.3.1" has unmet peer dependency "webpack@^5.0.0".
warning " > @cypress/webpack-dev-server@1.8.4" has unmet peer dependency "html-webpack-plugin@>=4".
warning " > @cypress/webpack-dev-server@1.8.4" has unmet peer dependency "webpack@>=4".
warning " > @cypress/webpack-dev-server@1.8.4" has unmet peer dependency "webpack-dev-server@>=3.0.0".
warning "@useoptic/cli > @useoptic/cli-server > @useoptic/ui > mini-css-extract-plugin@0.5.0" has unmet peer dependency "webpack@^4.4.0".
warning "@useoptic/cli > @useoptic/cli-server > @useoptic/ui > reactour@1.18.7" has unmet peer dependency "react-is@^16.8 || ^17.0.0-0".
warning "@useoptic/cli > @useoptic/cli-server > @useoptic/ui > styled-components@5.3.5" has unmet peer dependency "react-is@>= 16.8.0".
warning "@useoptic/cli > @useoptic/cli-server > @useoptic/ui > url-loader@1.1.2" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning "@useoptic/cli > @useoptic/analytics > joi-extract-type@15.0.8" has incorrect peer dependency "@hapi/joi@~15".
warning " > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
warning " > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "webpack@>= 4".
warning " > sass-loader@10.3.1" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning " > style-loader@2.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > ts-jest@26.5.6" has unmet peer dependency "jest@>=26 <27".
warning "vue-cli-plugin-vuetify > null-loader@4.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > vuetify-loader@1.7.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "vuetify-loader > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[4/4] Building fresh packages...
[12/24] ⡀ protobufjs
[13/24] ⡀ styled-components
[11/24] ⡀ @useoptic/diff-engine
[7/24] ⡀ sodium-native
error /home/StraemDk/default/opentogethertube-0.2.0/node_modules/@useoptic/diff-engine: Command failed.
Exit code: 1
Command: node scripts/install
Arguments:
Directory: /home/StraemDk/default/opentogethertube-0.2.0/node_modules/@useoptic/diff-engine
Output:
Downloading and installing binaries for diff-engine.
Could not install diff-engine.
 Error: Unsupported platform. Cannot install pre-built optic_diff for os.type=Linux os.arch=arm64. You can request support by opening a Github Issue at https://github.com/opticdev/optic/issues/new?title=Support%20for%20platform%20(os.type=Linux%20os.arch=arm64)&labels=feature%20request
    at install (/home/StraemDk/default/opentogethertube-0.2.0/node_modules/@useoptic/diff-engine/lib/index.js:250:11)
    at Object.<anonymous> (/home/StraemDk/default/opentogethertube-0.2.0/node_modules/@useoptic/diff-engine/scripts/install.js:25:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Comment by acunniffe** [comment]
Hey @Donkaos501  -- looks like this is an error from installing Optic <= 10. Optic 10 is deprecated so we won't be able to release any compatibility updates. 

If you'd like help migrating to Optic 11 I'd be happy to set up some time and look at opening a PR to opentogethertube. I've worked with @dyc3 in the past and love what you've built

**Comment by dyc3** [comment]
Ah, yeah we haven't updated optic in a while. I'm open to PRs to fix that.

**Comment by acunniffe** [comment]
Thanks @dyc3 -- wait for 11 to come out this week, I can ping you or open it myself 👍 . Glad you'all are still using 10.

**Comment by Donkaos501** [comment]
Thank you for helping :))

**Comment by acunniffe** [comment]
@Donkaos501 @dyc3  -- hey all, new docs are up https://www.useoptic.com/docs/track-changes

Optic 11 works by directly modifying the OpenAPI file now. Our optic spec has been deprecated. 

You should do one final OpenAPI export and then start using the new `oas update` command to patch the OpenAPI file. 

Happy to set up a few mins to help you port it over or review any PRs on the OSS repository to make sure it all goes smoothly

**Comment by Donkaos501** [comment]
```
root@instance-20220117-2026:/home/StraemDk/default/opentogethertube# yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning @segment/store@1.3.20: The engine "browser" appears to be invalid.
[3/4] Linking dependencies...
warning " > babel-jest@27.5.1" has unmet peer dependency "@babel/core@^7.8.0".
warning "babel-jest > babel-preset-jest@27.5.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > cypress-iframe@1.0.1" has unmet peer dependency "@types/cypress@^1.1.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > @cypress/webpack-dev-server@1.8.0" has unmet peer dependency "html-webpack-plugin@>=4".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > @cypress/webpack-dev-server@1.8.0" has unmet peer dependency "webpack@>=4".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > @cypress/webpack-dev-server@1.8.0" has unmet peer dependency "webpack-dev-server@>=3.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > @vue/cli-plugin-eslint@4.5.15" has incorrect peer dependency "eslint@>= 1.6.0 < 7.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > eslint-plugin-vue@6.1.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > fork-ts-checker-webpack-plugin@6.5.0" has unmet peer dependency "webpack@>= 4".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > sass-loader@10.2.0" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > style-loader@2.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > ts-loader@9.2.6" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > vuetify-loader@1.7.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > @vue/cli-plugin-eslint > eslint-loader@2.2.1" has incorrect peer dependency "eslint@>=1.6.0 <7.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > vue-cli-plugin-vuetify > null-loader@4.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-client > vuetify-loader > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-server > @useoptic/cli > @useoptic/cli-server > express-graphql@0.12.0" has unmet peer dependency "graphql@^14.7.0 || ^15.3.0".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-server > @useoptic/cli > @useoptic/cli-server > @useoptic/ui-v2 > react-markdown@5.0.3" has unmet peer dependency "@types/react@>=16".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-server > @useoptic/cli > @useoptic/cli-server > @useoptic/ui-v2 > react-scroll-into-view-if-needed@2.1.7" has unmet peer dependency "prop-types@^15.6.1".
warning "workspace-aggregator-618f2464-0ee4-4ec3-8202-5bf28d33b3b5 > ott-server > @useoptic/cli > @useoptic/cli-server > @useoptic/ui-v2 > react-scroll-into-view-if-needed@2.1.7" has incorrect peer dependency "react@^16.0.0".
[4/4] Building fresh packages...
[1/20] ⠐ cypress
[9/20] ⠐ browser-tabs-lock
[7/20] ⠐ @useoptic/optic-engine-native
[4/20] ⠐ sodium-native
error /home/StraemDk/default/opentogethertube/node_modules/@useoptic/optic-engine-native: Command failed.
Exit code: 1
Command: node scripts/install
Arguments:
Directory: /home/StraemDk/default/opentogethertube/node_modules/@useoptic/optic-engine-native
Output:
Downloading and installing binaries for optic-engine-native.
Could not install optic-engine-native.
 Error: Unsupported platform. Cannot install pre-built optic_diff for os.type=Linux os.arch=arm64. You can request support by opening a Github Issue at https://github.com/opticdev/optic/issues/new?title=Support%20for%20platform%20(os.type=Linux%20os.arch=arm64)&labels=feature%20request
    at install (/home/StraemDk/default/opentogethertube/node_modules/@useoptic/optic-engine-native/lib/index.js:246:11)
    at Object.<anonymous> (/home/StraemDk/default/opentogethertube/node_modules/@useoptic/optic-engine-native/scripts/install.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
```

I'm not really familiar how to fix this now, so if anyone can tell me how to fix it step by step.
That would be nice :))

**Comment by acunniffe** [comment]
Morning -- this looks like it might be the result of having been using the optic10 native pieces. They might conflict with optic11 namespace. 

Can you run `npm -g uninstall @useoptic/optic-engine-native` or `yarn global remove @useoptic/optic-engine-native`? 

I think if you get old dep off your system and reinstall Optic you should be in good shape.

**Comment by acunniffe** [comment]
Closing this now, please let us know if you have any other issues getting it to install
