### ISSUE TITLE
There's a "capturedError: write EPIPE" and exception

### ISSUE THREAD

**Issue by williamxin** [opticdev/optic#1360]
When I run 
`oas capture --proxy http://localhost:8080 > traffic.har`
then I got an error
`» Proxy created. Redirect traffic you want to capture to https://localhost:8000
 help  Press [ Enter ] to finish capturing requests
⠏ 1 requests captured
⠋ 1 requests capturedError: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Object.moveCursor (node:internal/readline/callbacks:85:17)
    at C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\commands\capture.js:247:84
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\commands\capture.js:56:23)
⠼ 1 requests captured`

I run this command:
`oas openapi.yml status --har traffic.har`
and I got this err:
`This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Malformed path '\v2\pet'
    at PathComponents.fromPath (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\index.js:106:19)
    at OperationQueries.matchPathPattern (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\queries.js:148:51)
    at OperationQueries.findPathPattern (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\queries.js:133:41)
    at SpecOperationDiffTraverser.<anonymous> (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\traversers.js:96:26)
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\traversers.js:24:23)
    at Object.next (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\traversers.js:5:53)
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\index.js:9:139)
    at Object.next (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\index.js:5:53)
    at Function.<anonymous> (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\streams\undocumented.js:123:88)
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\streams\undocumented.js:47:23)`

How can I solve this problem?

Thanks

**Comment by acunniffe** [comment]
Are you on a windows machine? It looks like one of the native dependencies we include to work with urls is assuming those are files and using the platform specific forward and back slashes `/` or `\`. Marking this as a bug and getting a fix up

**Comment by acunniffe** [comment]
@williamxin  -- I've opened https://github.com/opticdev/optic/pull/1362 and will get it into the project shortly. Thanks for reporting this

**Comment by acunniffe** [comment]
It's merged, we don't release on the weekends so it'll be in a build next week.

**Comment by acunniffe** [comment]
@williamxin -- released in the latest version. I've tested on a windows box, but please let me know if the problem persists or you need help with anything else!

**Comment by williamxin** [comment]
> @williamxin -- released in the latest version. I've tested on a windows box, but please let me know if the problem persists or you need help with anything else!

Sorry, the problem still exists on my windows, my oas version is 0.33.3
I don't know wether I have got the property version

**Comment by williamxin** [comment]
` yongxin@DESKTOP-YONGXIN  D:\gogs  oas capture --proxy http://localhost:8080 > traffic.har
 » Proxy created. Redirect traffic you want to capture to https://localhost:8000
 help  Press [ Enter ] to finish capturing requests
⠼ 61 requests captured
⠴ 61 requests capturedError: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Object.moveCursor (node:internal/readline/callbacks:85:17)
    at C:\Users\yongxin\scoop\persist\nodejs\bin\node_modules\@useoptic\optic\node_modules\@useoptic\openapi-cli\build\commands\capture.js:247:84
    at step (C:\Users\yongxin\scoop\persist\nodejs\bin\node_modules\@useoptic\optic\node_modules\@useoptic\openapi-cli\build\commands\capture.js:56:23)
✔ 61 requests written`

**Comment by williamxin** [comment]
`

 yongxin@DESKTOP-YONGXIN  D:\gogs  oas capture --proxy http://localhost:8080 > traffic.har
 » Proxy created. Redirect traffic you want to capture to https://localhost:8000
 help  Press [ Enter ] to finish capturing requests
⠼ 61 requests captured
⠴ 61 requests capturedError: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Object.moveCursor (node:internal/readline/callbacks:85:17)
    at C:\Users\yongxin\scoop\persist\nodejs\bin\node_modules\@useoptic\optic\node_modules\@useoptic\openapi-cli\build\commands\capture.js:247:84
    at step (C:\Users\yongxin\scoop\persist\nodejs\bin\node_modules\@useoptic\optic\node_modules\@useoptic\openapi-cli\build\commands\capture.js:56:23)
✔ 61 requests written

`
