### ISSUE TITLE
Using OAS with HAR throws an error (path pattern for can not be found for paths with host and / or protocol)

### ISSUE THREAD

**Issue by tgalopin** [opticdev/optic#1406]
Hi!

I am experimenting with optic (love the idea!) and I stumble an issue I'm unable to tackle.

Given the following HAR file:

```json
{
    "log": {
        "version": "1.3",
        "creator": {
            "name": "Selency",
            "version": "6.1.7"
        },
        "browser": {
            "name": "Symfony KernelBrowser",
            "version": "6.1.7"
        },
        "entries": [
            {
                "startedDateTime": "2022-11-14T10:51:30+00:00",
                "time": 1081,
                "cache": [],
                "timings": [],
                "request": {
                    "httpVersion": "HTTP\/1.1",
                    "method": "GET",
                    "url": "http:\/\/localhost\/products\/78fefd722eaf36ee80f6db8130a1838a",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "host",
                            "value": "localhost"
                        },
                        {
                            "name": "user-agent",
                            "value": "Symfony BrowserKit"
                        },
                        {
                            "name": "accept-language",
                            "value": "fr_FR"
                        },
                        {
                            "name": "accept-charset",
                            "value": "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
                        },
                        {
                            "name": "x-php-ob-level",
                            "value": "0"
                        }
                    ],
                    "queryString": [],
                    "headersSize": 158,
                    "bodySize": 158
                },
                "response": {
                    "httpVersion": "HTTP\/1.1",
                    "status": 200,
                    "statusText": "OK",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "cache-control",
                            "value": "no-cache, private"
                        },
                        {
                            "name": "date",
                            "value": "Mon, 14 Nov 2022 10:51:30 GMT"
                        },
                        {
                            "name": "content-type",
                            "value": "application\/json"
                        },
                        {
                            "name": "content-version",
                            "value": "1"
                        },
                        {
                            "name": "deprecation",
                            "value": "Tue, 18 Oct 2022 00:00:00 GMT"
                        },
                        {
                            "name": "content-language",
                            "value": "fr_FR"
                        },
                        {
                            "name": "vary",
                            "value": "Accept-Language"
                        },
                        {
                            "name": "x-debug-token",
                            "value": "42c4d9"
                        },
                        {
                            "name": "x-robots-tag",
                            "value": "noindex"
                        }
                    ],
                    "redirectURL": "",
                    "headersSize": 305,
                    "bodySize": 2351,
                    "content": {
                        "compression": 0,
                        "size": 2046,
                        "mimeType": "application\/json; charset=utf-8",
                        "text": "..."
                    }
                }
            }
        ]
    }
}
```

When running OAS with my documentation, I get and error:

```
$ oas openapi.yaml status --har tests.har
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Invariant Violation: path pattern for can not be found for paths with host and / or protocol
    at new InvariantError (/Users/tgalopin/.config/yarn/global/node_modules/ts-invariant/lib/invariant.js:16:28)
    at invariant (/Users/tgalopin/.config/yarn/global/node_modules/ts-invariant/lib/invariant.js:28:15)
    at OperationQueries.findPathPattern (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/queries.js:128:36)
    at SpecOperationDiffTraverser.<anonymous> (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/traversers.js:96:26)
    at step (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/traversers.js:24:23)
    at Object.next (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/traversers.js:5:53)
    at step (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/index.js:9:139)
    at Object.next (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/index.js:5:53)
    at Function.<anonymous> (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/streams/undocumented.js:123:88)
    at step (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/streams/undocumented.js:47:23)
```

I tried various updates to the HAR file without success. Any idea what may be the issue?

Thanks!

**Comment by acunniffe** [comment]
Hey @tgalopin -- great to meet your! That's not a very helpful error message, sorry it does not say more. 

I wonder if you have any servers defined in the OpenAPI file you are trying to keep up-to-date https://swagger.io/docs/specification/api-host-and-base-path/ 

If you did not define any servers it wouldn't try to be clever, but if you do, and `localhost` is not one of them, the matching could fail. 

I'll keep eyes on this today and help you figure it out. feel free to book me https://calendly.com/optic-onboarding/optic-office-hours

**Comment by tgalopin** [comment]
Ah the issue may be indeed the fact that I do use servers and localhost isn't in them. I'll try tomorrow, thanks!

**Comment by tgalopin** [comment]
I updated my HAR file to look like this:

```
{
    "log": {
        "version": "1.3",
        "creator": {
            "name": "Selency",
            "version": "6.1.7"
        },
        "browser": {
            "name": "Symfony KernelBrowser",
            "version": "6.1.7"
        },
        "entries": [
            {
                "startedDateTime": "2022-11-14T10:51:30+00:00",
                "time": 1081,
                "cache": [],
                "timings": [],
                "request": {
                    "httpVersion": "HTTP\/1.1",
                    "method": "GET",
                    "url": "https:\/\/api.selency.local\/products\/78fefd722eaf36ee80f6db8130a1838a",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "host",
                            "value": "localhost"
                        },
                        {
                            "name": "user-agent",
                            "value": "Symfony BrowserKit"
                        },
                        {
                            "name": "accept-language",
                            "value": "fr_FR"
                        },
                        {
                            "name": "accept-charset",
                            "value": "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
                        },
                        {
                            "name": "x-php-ob-level",
                            "value": "0"
                        }
                    ],
                    "queryString": [],
                    "headersSize": 158,
                    "bodySize": 158
                },
                "response": {
                    "httpVersion": "HTTP\/1.1",
                    "status": 200,
                    "statusText": "OK",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "cache-control",
                            "value": "no-cache, private"
                        },
                        {
                            "name": "date",
                            "value": "Mon, 14 Nov 2022 10:51:30 GMT"
                        },
                        {
                            "name": "content-type",
                            "value": "application\/json"
                        },
                        {
                            "name": "content-version",
                            "value": "1"
                        },
                        {
                            "name": "deprecation",
                            "value": "Tue, 18 Oct 2022 00:00:00 GMT"
                        },
                        {
                            "name": "content-language",
                            "value": "fr_FR"
                        },
                        {
                            "name": "vary",
                            "value": "Accept-Language"
                        },
                        {
                            "name": "x-debug-token",
                            "value": "42c4d9"
                        },
                        {
                            "name": "x-robots-tag",
                            "value": "noindex"
                        }
                    ],
                    "redirectURL": "",
                    "headersSize": 305,
                    "bodySize": 2351,
                    "content": {
                        "compression": 0,
                        "size": 2046,
                        "mimeType": "application\/json; charset=utf-8",
                        "text": "..."
                    }
                }
            }
        ]
    }
}
```

And my openapi.yaml file contains:

```
servers:
  - url: https://api.selency.local
  - url: https://api.selency-staging.com
  - url: https://api.selency.com
```

But the issue persists:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Invariant Violation: path pattern for can not be found for paths with host and / or protocol
    at new InvariantError (/Users/tgalopin/.config/yarn/global/node_modules/ts-invariant/lib/invariant.js:16:28)
    at invariant (/Users/tgalopin/.config/yarn/global/node_modules/ts-invariant/lib/invariant.js:28:15)
    at OperationQueries.findPathPattern (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/queries.js:128:36)
    at SpecOperationDiffTraverser.<anonymous> (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/traversers.js:96:26)
    at step (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/traversers.js:24:23)
    at Object.next (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/traversers.js:5:53)
    at step (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/index.js:9:139)
    at Object.next (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/diffs/index.js:5:53)
    at Function.<anonymous> (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/streams/undocumented.js:123:88)
    at step (/Users/tgalopin/.config/yarn/global/node_modules/@useoptic/openapi-cli/build/operations/streams/undocumented.js:47:23)
```

**Comment by acunniffe** [comment]
Hey @tgalopin  -- I think it may be caused by rules that are too strict on the server URLs. Can you try commenting out the servers altogether in the openapi file and running it? Just to help isolate what is going on here?

**Comment by IMSoP** [comment]
I have just run into this same bug. Substituting the error message for the variable it's asserting on (`pathPattern`), it seems that something has trimmed off the leading `/` from the path.

I can trigger it reliably by adding a single server to an otherwise empty OAS document.

Run `yarn oas new --oas-version 3.1.0 test.yaml` to give a template `test.yaml`:

```yaml
openapi: 3.1.0
info:
  title: Untitled service
  version: 1.0.0
paths: {}
```

And create `test.har` with the following:

```json
{
    "log": {
        "version": "1.3",
        "creator": {"name": "example","version": "1"},
        "entries": [
            {
                "cache": [],
                "startedDateTime": "2022-11-04T13:00:00.825+00:00",
                "request": {
                    "httpVersion": "HTTP\/1.1",
                    "method": "GET",
                    "url": "https:\/\/example.com\/example",
                    "queryString": [],
                    "headers": [],
                    "headersSize": -1,
                    "cookies": [],
                    "bodySize": 0
                },
                "time": 1,
                "timings": {"send": -1, "wait": 1, "receive": -1},
                "response": {
                    "httpVersion": "HTTP\/1.1",
                    "status": 200,
                    "statusText": "OK",
                    "redirectURL": "",
                    "headers": [],
                    "headersSize": -1,
                    "cookies": [],
                    "bodySize": 16,
                    "content": {
                        "size": 16,
                        "mimeType": "application\/json",
                        "text": "{\"success\":true}"
                    }
                }
            }
        ]
    }
}
```

Run `yarn oas status --har test.har test.yaml` and get successful output.

Now edit `test.yaml` to add a single server URL; it doesn't seem to matter what URL you add.

```yaml
openapi: 3.1.0
info:
  title: Untitled service
  version: 1.0.0
paths: {}
servers:
  - url: https://example.com
```

Run `yarn oas status --har test.har test.yaml` and the error appears.

**Comment by IMSoP** [comment]
I've narrowed it down further! The bug triggers if the server URL has no path component, only a scheme and domain.

Using the following `test.yaml` processes successfully:

```yaml
openapi: 3.1.0
info:
  title: Untitled service
  version: 1.0.0
paths: {}
servers:
  - url: https://example.com/v1
```

Note that a trailing slash is *not* enough, that is the following *fails*:

```yaml
openapi: 3.1.0
info:
  title: Untitled service
  version: 1.0.0
paths: {}
servers:
  - url: https://example.com/
```

**Comment by acunniffe** [comment]
Thanks for digging deeper @IMSoP - this is very helpful reproduction. We'll take a deeper look into this now 👍 

Offending line appears to be here https://github.com/opticdev/optic/blob/8052e3cc000ce20642d3e10c03f8e370fe605443/projects/openapi-cli/src/operations/streams/undocumented.ts#L80

If I had to be it needs to be replaced with UrlJoin https://www.npmjs.com/package/url-join
