### ISSUE TITLE
Error: Invalid reference token: items

### ISSUE THREAD

**Issue by mmaxin** [opticdev/optic#1929]
**Describe the bug**
Error thrown when executing `optic update openapi.yaml --all` with results found (recreated by manually adding endpoints one by one and the error occurred on some specific ones)
```
root@186156616a7a:/# optic update openapi.yaml --all
» Documenting new operations...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Invalid reference token: items
    at Object.get (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@useoptic/json-pointer-helpers/build/json-pointers/json-pointer-helpers.js:24:19)
    at requiredPatches$ (/usr/local/lib/node_modules/@useoptic/optic/build/commands/oas/shapes/patches/generators/required.js:64:64)
    at tryCatch (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at tryCatch (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at maybeInvokeDelegate (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:141:18)
    at Generator.<anonymous> (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:114:32)
    at Generator.next (/usr/local/lib/node_modules/@useoptic/optic/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at Object.n (/usr/local/lib/node_modules/@useoptic/optic/build/commands/oas/shapes/streams/patches.js:14:771)
```
**To Reproduce**
1. Pull a new node image (`docker pull node`) 
2. Run container `docker run -it --net container:{PROJECT_CONTAINER} node bash`
3. In Node container execute `npm install -g @useoptic/optic`
4. Followed by `optic new openapi.yaml`, `optic capture openapi.yaml http://localhost:8080`
5. This captured all the requests generated by `golang` request calls (See additional context section)
6. `optic update openapi.yaml --all` throws unexpected error 

**Expected behavior**
openapi file populated with the found results 

**Screenshots**

**Details (please complete the following information):**
 - OS and version: Mac OS 13.3.1 (Docker version 20.10.21-rd)
 - Optic version: 0.43.1
 - NodeJS version: v20.2.0

**Additional context**
```
root@186156616a7a:/# optic capture openapi.yaml http://localhost:8080
» Proxy running on https://localhost:8001. System proxy updated
automatic proxy configuration is not supported on linux
 help  Press [ Enter ] to finish capturing requests

Not seeing any traffic captured? Make sure your HTTP Client is using the proxy: https://www.useoptic.com/docs/oas-reference/client-guides
✔ 1118 requests captured

» Verifying API behavior with traffic from last 2 captures. Reset captures $ optic oas capture clear openapi.yaml`

...project details...

Document all new operations with $ optic update openapi.yaml --all
Document individual operations with $ optic update openapi.yaml "[method] /[path]" ...

```

`optic verify openapi.yaml`
```
root@186156616a7a:/# optic verify openapi.yaml


» Verifying API behavior with traffic from last 2 captures. Reset captures $ optic oas capture clear openapi.yaml`

...project details...

Document all new operations with $ optic update openapi.yaml --all
Document individual operations with $ optic update openapi.yaml "[method] /[path]" ...

 API Behavior Report

 Total Requests          : 0
 Diffs                   : 0
 Undocumented operations : 47
 Undocumented bodies     : 0

 Coverage Report 0%

OpenAPI and implementation are out of sync. Exiting 1
```

**Comment by niclim** [comment]
Hi, thanks for the detailed bug report! I'll take a look into this and see what I can find.

If you don't mind, can you try narrow down which endpoint response is causing this + extracting the har for that request/response (it'll be helpful to track down the code path this is failing at).

The easiest way to do this is:
- Run the `capture` command and only send traffic to the endpoint that fails to document
- A har file is saved under `$TMPDIR/optic/captures/{spechash}`
  - if your running this on a docker image, there should only be one spechash
  - if `$TMPDIR` isn't set in your docker image, you can get the tmpdir from node/js:

```javascript
const os = require('os');
const tmpdir = os.tmpdir();
console.log(tmpdir)
```

**Comment by mmaxin** [comment]
Hi @niclim please find one example I was able to track down (the testsuite I am running is pretty huge with intertwined test cases) 
[1684424272265.har.zip](https://github.com/opticdev/optic/files/11509206/1684424272265.har.zip)

**Comment by mmaxin** [comment]
Hey @niclim it works, all green!
