### ISSUE TITLE
sentry error running binary/docker builds of v0.50.5

### ISSUE THREAD

**Issue by notnmeyer** [opticdev/optic#2359]
```
➜ optic --version
pkg/prelude/bootstrap.js:1872
      throw error;
      ^
Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
    at new NodeError (node:internal/errors:388:5)
    at node:inspector:23:9
    at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:329:7)
    at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:269:10)
    at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
    at Module._load (node:internal/modules/cjs/loader:813:15)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/optic/node_modules/@sentry/node/cjs/anr/index.js:5:19) {
  code: 'ERR_INSPECTOR_NOT_AVAILABLE'
}
Node.js v18.5.0
```

looks like a fix is pending, https://github.com/getsentry/sentry-javascript/pull/9149

**Comment by notnmeyer** [comment]
workaround for the moment is to install the npm package
