### ISSUE TITLE
Dependabot Build Error

### ISSUE THREAD

**Issue by sennyeya** [opticdev/optic#2528]
**Describe the bug**
https://github.com/backstage/backstage/pull/21169
Build failing with a weird internal issue for Optic, might be a weirdness with our spec but the spec should be valid.

**To Reproduce**
See dependabot build.

**Expected behavior**
No error.

**Details (please complete the following information):**
 - OS and version: Ubuntu Github Action
 - Optic version: newest
 - NodeJS version: 18.0.0

**Comment by notnmeyer** [comment]
https://github.com/backstage/backstage/actions/runs/6815568714/job/18535099204?pr=21169

```
TypeError: Cannot read properties of undefined (reading 'headers')
    at generateResponseHeaderPatches (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/capture/patches/patchers/spec/response-headers.js:73:60)
    at generateResponseHeaderPatches.next (<anonymous>)
    at SpecPatches.responseAdditions (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/capture/patches/patchers/spec/patches.js:116:63)
    at responseAdditions.next (<anonymous>)
    at generateEndpointSpecPatches (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/capture/patches/patches.js:73:20)
    at async Object.collect (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/oas/lib/async-tools.js:132:18)
    at async diffExistingEndpoint (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/capture/actions/documented.js:185:52)
    at async processCaptures (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/capture/capture.js:332:9)
    at async /home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/commands/capture/capture.js:144:25
    at async Command.<anonymous> (/home/runner/work/backstage/backstage/node_modules/@useoptic/optic/build/error-handler.js:18:14)
Cannot read properties of undefined (reading 'headers')
  console.log
    {"error":{"name":"Error","message":"There was a problem performing the search query: Query error message"},"request":{"method":"GET","url":"/query"},"response":{"statusCode":500}}
      at Object.<anonymous> (service/router.test.ts:83:15)
```

**Comment by niclim** [comment]
Ah I see - looks like the capture flow is breaking when there's `5xx` responses recorded. I'm building a fix https://github.com/opticdev/optic/pull/2529 - will update here when that's out

**Comment by niclim** [comment]
@sennyeya - `0.52.1` is out - could you try that and see if that fixes the issue - thanks!

**Comment by sennyeya** [comment]
Will do, thanks!
