### ISSUE TITLE
Cannot use diff-all offline

### ISSUE THREAD

**Issue by jgresty** [opticdev/optic#2723]
**Describe the bug**
Trying to run diff-all without setting an OPTIC_TOKEN results in the error:
```
Error making request to Optic
It looks like your token is invalid (this could mean your token has expired, or it has been revoked).
```

**To Reproduce**
1. unset OPTIC_TOKEN
2. Run diff-all

**Expected behavior**
Optic will diff specs without calling out to the web service.

**Details (please complete the following information):**
 - Optic version: v0.53.16

**Additional context**
It appears that an exception is thrown when looking up [generatedDetails](https://github.com/opticdev/optic/blob/476f3ef99746aaf52584c9f101ef4ab831851e7c/projects/optic/src/commands/diff/diff-all.ts#L273), partial trace:
```
    at handleJsonResponse (@useoptic/optic/build/client/JsonHttpClient.js:32:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getOrganizationFromToken (@useoptic/optic/build/utils/organization.js:17:7)
    at async getDetailsForGeneration (@useoptic/optic/build/utils/generated.js:19:18)
    at async computeAll (@useoptic/optic/build/commands/diff/diff-all.js:152:28)
```

This issue was masked behind the `--generated` flag prior to v0.48.10-0 however that version [made this option always enabled](https://github.com/opticdev/optic/commit/3bd80b95ef9337e399719bec8f27f67091e4e3ef).

**Comment by niclim** [comment]
A fix is included as part of `0.54.4` - it should avoid calling out if there's no token set - let me know if there's anything else we can help with!
