### ISSUE TITLE
Optic 1.0.5 just uses 100% of my CPU and nothing happens

### ISSUE THREAD

**Issue by mohithg** [opticdev/optic#5]
- I downloaded optic from the useoptic.com website, and its not working in MAC

**Comment by acunniffe** [comment]
@mohithg sorry to hear that. Sounds like an issue starting up. 

Here's how you can help us debug:

run "system_profiler" email the results to aidan@useoptic.com
questions from me: 
1. Does the Optic dot appear on your screen with the loader? 
2. what does "curl localhost:30333" output? 
 
Thanks! We'll get this figured out as quickly as we can. Thanks for supporting the project -- we're still early.

**Comment by mohithg** [comment]
Sorry for the delay, my OS is MacOS High Sierra, 

1. I do see the optic dot appearing on the bottom right of my screen with the loader
2. `curl localhost:30333
curl: (7) Failed to connect to localhost port 30333: Connection refused`

**Comment by acunniffe** [comment]
Interesting -- this is definitely a different issue then. Thank you for sharing. It sounds like the local Optic server (runs on port 30333) isn't starting up properly. If I had to guess it's an issue with the server binding to the port that's causing the main thread to hang and lock up 100%.

Are you using a corporate computer with strict firewalls installed? 

Here are a few more steps to try(use your own paths): 
1. run `/Applications/Optic.app/Contents/Resources/jre/Contents/Home/bin/java` -- let's see if the embedded JRE is working on your machine. Does this also hang or do you get the normal man output you'd expect? 
2. run `/Applications/Optic.app/Contents/Resources/jre/Contents/Home/bin/java --jar /Applications/Optic.app/Contents/Resources/embedded/server/server-assembly.jar` -- try to run the server by hand

**Comment by mohithg** [comment]
I'm not behind corporate firewalls. 

The output of server-assembly.jar 
```
Exception in thread "main" java.lang.Error: No opticmarkdown found in config.yml
	at com.opticdev.sdk.markdown.CallOpticMarkdown$.$anonfun$scriptPath$2(CallOpticMarkdown.scala:24)
	at scala.util.Failure.getOrElse(Try.scala:218)
	at com.opticdev.sdk.markdown.CallOpticMarkdown$.scriptPath(CallOpticMarkdown.scala:24)
	at com.opticdev.sdk.markdown.CallOpticMarkdown$.script$lzycompute(CallOpticMarkdown.scala:28)
	at com.opticdev.sdk.markdown.CallOpticMarkdown$.script(CallOpticMarkdown.scala:28)
	at com.opticdev.sdk.markdown.CallOpticMarkdown$.version(CallOpticMarkdown.scala:31)
	at com.opticdev.sdk.markdown.CallOpticMarkdown$.isValid(CallOpticMarkdown.scala:47)
	at com.opticdev.server.http.Lifecycle$.startup(Lifecycle.scala:42)
	at com.opticdev.server.http.Lifecycle$.delayedEndpoint$com$opticdev$server$http$Lifecycle$1(Lifecycle.scala:39)
	at com.opticdev.server.http.Lifecycle$delayedInit$body.apply(Lifecycle.scala:19)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.opticdev.server.http.Lifecycle$.main(Lifecycle.scala:19)
	at com.opticdev.server.http.Lifecycle.main(Lifecycle.scala)
```

**Comment by acunniffe** [comment]
@mohithg Can you try out the new version. We've moved everything to a CLI: https://www.npmjs.com/package/optic-cli
